version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"  # Root-level docker-compose.yml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "docker"
    directory: "/authentik"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "docker"
    directory: "/influxdb"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "docker"
    directory: "/nodered"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "docker"
    directory: "/portainer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "docker"
    directory: "/traefik"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
