include:
  - ./traefik/docker-compose.yml
  - ./portainer/docker-compose.yml
  - ./nodered/docker-compose.yml

services:
  portainer:
    depends_on:
      - traefik
  
  node-red:
    depends_on:
      - traefik