services:
  traefik:
    image: docker.io/library/traefik:v3.5.0
    container_name: traefik
    ports:
      - 443:443
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ${BASE_PATH}/traefik/config:/etc/traefik:rw
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CF_DNS_API_EMAIL=${CLOUDFLARE_EMAIL_ADDRESS}
    command:
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true

      # Entrypoints
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --entrypoints.websecure.http.tls.options=securetls@file

      # Certificates
      - --certificatesresolvers.cloudflare.acme.storage=/etc/traefik/certs/cloudflare-acme.json
      - --certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53

      # Dashboard
      - --api.dashboard=true

      # Metrics
      - --metrics.prometheus=true
      - --metrics.prometheus.manualrouting=true

      # Logging
      - --log.level=ERROR
      - --accesslog=true

    labels:
      - traefik.enable=true

      # 🛡️ Secure Headers Middleware
      - traefik.http.middlewares.secureHeaders.headers.frameDeny=true
      - traefik.http.middlewares.secureHeaders.headers.sslRedirect=true
      - traefik.http.middlewares.secureHeaders.headers.contentTypeNosniff=true
      - traefik.http.middlewares.secureHeaders.headers.browserXssFilter=true
      - traefik.http.middlewares.secureHeaders.headers.referrerPolicy=no-referrer-when-downgrade
      - traefik.http.middlewares.secureHeaders.headers.permissionsPolicy=geolocation=(), microphone=()
      - traefik.http.middlewares.secureHeaders.headers.stsSeconds=31536000
      - traefik.http.middlewares.secureHeaders.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.secureHeaders.headers.stsPreload=true

      # 🤖 Robot Headers Middleware
      - traefik.http.middlewares.robotHeaders.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow

      # 🧠 Content-Type Detection Middleware
      - traefik.http.middlewares.autodetect.contenttype=true

      # 📊 Metrics Router (HTTPS only)
      - traefik.http.routers.metrics.entrypoints=websecure
      - traefik.http.routers.metrics.rule=Host(`metrics.${BASE_DOMAIN_NAME}`) && Path(`/prometheus`)
      - traefik.http.routers.metrics.service=prometheus@internal
      - traefik.http.routers.metrics.tls=true
      - traefik.http.routers.metrics.tls.certresolver=cloudflare
      - traefik.http.routers.metrics.tls.options=securetls@file
      - traefik.http.routers.metrics.middlewares=traefik-auth,secureHeaders@docker,robotHeaders@docker,autodetect@docker

      # 📋 Dashboard Router (HTTPS only)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`dash.${BASE_DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.options=securetls@file
      - traefik.http.routers.traefik.middlewares=traefik-auth,secureHeaders@docker,robotHeaders@docker,autodetect@docker

    networks:
      - frontend
    restart: unless-stopped
