---
services:
  traefik:
    image: docker.io/library/traefik:v3.5.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # --> (Optional) Enable Dashboard, don't do in production
      # - 8080:8080
      # <--
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ${BASE_PATH}/config/:/etc/traefik/:ro
      - ${BASE_PATH}/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true 