services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/London
    labels:
      - traefik.enable=true
      - traefik.http.services.node-red.loadbalancer.server.port=1880
      - traefik.http.routers.node-red.service=node-red
      - traefik.http.routers.node-red.entrypoints=websecure
      - traefik.http.routers.node-red.rule=Host(`node-red.$BASE_DOMAIN_NAME`)
      - traefik.http.routers.node-red.tls=true
      - traefik.http.routers.node-red.tls.certresolver=cloudflare
    networks:
      - frontend
    user: $USER
    # ports:
      # - "1880:1880"
    volumes:
      - $BASE_PATH/nodered/data:/data
    depends_on:
      - traefik
      - db
      - server
      - worker