name: node-red
services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/London
    user: $USER
    ports:
      - "1880:1880"
    volumes:
      - $BASE_PATH/nodered/data:/data
