---
services:
  influxdb:
    container_name: influxdb
    image: docker.io/library/influxdb:2.7.12-alpine
    # (Optional) remove this section when using traefik
    # ports:
      # - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
      # (Optional) when using certificate
      # - /etc/ssl/cert.pem/:/etc/ssl/cert.pem  # (optional) if you're using self-signed certs
      # - /etc/ssl/cert-key.pem/:/etc/ssl/cert-key.pem  # (optional) if you're using self-signed certs
    # (Optional) when using certificate
    # command: influxd --tls-cert=/etc/ssl/cert.pem --tls-key=/etc/ssl/cert-key.pem  # (optional) if you're using self-signed certs
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
    # (Optional) change retention time
    #   - DOCKER_INFLUXDB_INIT_RETENTION=1w  # (optional) configure data retention 1 week
    # (Optional) add admin token
    #   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token  # (optional) set admin token
    # (Optional) when using traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
      - traefik.http.services.influxdb.loadbalancer.server.scheme=https
      - traefik.http.routers.influxdb-https.entrypoints=websecure
      - traefik.http.routers.influxdb-https.rule=Host(`influxdb.${BASE_DOMAIN_NAME}`)
      - traefik.http.routers.influxdb-https.tls=true
      - traefik.http.routers.influxdb-https.tls.certresolver=cloudflare
    # (Optional) when using custom network
    networks:
      - frontend
    restart: unless-stopped